# Generated by Django 5.0.1 on 2024-01-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='вага')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='нотатка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'продукти',
                'verbose_name_plural': 'продукти',
                'ordering': ['order__done', '-order__user'],
            },
        ),
    ]
