# Generated by Django 5.0.1 on 2024-01-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='продукт')),
                ('price', models.FloatField(default=0, verbose_name='ціна')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукт',
                'ordering': ['product', 'price'],
            },
        ),
    ]
