# Generated by Django 5.0.1 on 2024-01-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product', 'price'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукт'},
        ),
    ]
