# Generated by Django 5.0.1 on 2024-01-15 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=150, unique=True, verbose_name='public id')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('image_url', models.CharField(max_length=150, unique=True, verbose_name='image url')),
                ('qr_code_url', models.CharField(max_length=150, unique=True, verbose_name='qr code url')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment', verbose_name='comment')),
                ('tags', models.ManyToManyField(to='tags.tag', verbose_name='tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
