# Generated by Django 5.0.1 on 2024-01-15 13:11

import django.core.validators
import pictures.models
import pictures.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to=pictures.models.image_directory_path, validators=[pictures.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='image'),
            preserve_default=False,
        ),
    ]
